version: "2"
services:
  practice_docker: 
    image: robmasango/addressapp
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/useraddress
      - PORT=3000   
  db:
    image: postgres
    volumes:
    - ./db_createtable.sql:/docker-entrypoint-initdb.d/db_createtable.sql
    - ./db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=practicedocker